### ISSUE TITLE
program can't find voicemeeter8x64.exe

### ISSUE THREAD

**Issue by jhcaps** [maddjester/meeter-maid#1]
Traceback (most recent call last):
  File "C:\Users\maddjester\Desktop\meeter_maid\app.py", line 24, in <module>
  File "C:\Users\maddjester\Desktop\meeter_maid\app.py", line 15, in skip_wait
  File "pymem\__init__.py", line 45, in __init__
  File "pymem\__init__.py", line 215, in open_process_from_name
pymem.exception.ProcessNotFound: Could not find process: voicemeeter8x64.exe

**Comment by maddjester** [comment]
What version of voicemeeter are you using?

**Comment by jhcaps** [comment]
it should be 3.0.2.8
